# .github/actions/deploy/action.yml
name: deploy

permissions:
  contents: read
  id-token: write

inputs:
  working-directory:
    required: true
    description: 作業ディレクトリの指定
  app-name:
    required: true
    description: アプリケーション名
  stage:
    required: true
    description: デプロイ先の環境名
  aws-account-id:
    required: true
    description: デプロイ先のAWSアカウントID

runs:
  using: composite
  steps:
    # .lambroll-versionのバージョンを取得する
    - name: set environment variables
      shell: bash
      run: echo "LAMBROLL_VERSION=v0.14.7" >> $GITHUB_ENV

    # AWSへのアクセスは、OIDC認証を使用しています
    # https://docs.github.com/ja/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ap-northeast-1
        # role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ inputs.app-name }}-${{ inputs.stage }}-deploy
        role-to-assume: arn:aws:iam::308565263693:role/oidc-example-role
        # role-session-name: github-actions-${{ github.run_id }}

    # # lambrollは、公式で配布されているアクションを使用しています
    # # https://github.com/fujiwara/lambroll#github-actions
    # - uses: fujiwara/lambroll@v0
    #   with:
    #     version: ${{ env.LAMBROLL_VERSION }}

    # - name: deploy
    #   shell: bash
    #   working-directory: ${{ inputs.working-directory }}
    #   run: デプロイ処理は省略